### PR TITLE
Slight design changes to User Interface

### PR DESCRIPTION
**Pull request by LeNitrous**
image
image

Aside from this, there are also refactors to some namespaces and general cleanup.

### CODE REVIEW

**Comment by sr229** [comment]
Mentioning Vignette once more is a bit redundant so just title it as "Visit us" or similar in the website, or replace it with something else

**Review by sr229 — CHANGES_REQUESTED** [review]
Check suggestion before I merge since it doesn't flow right to mention our name again

**Comment by LeNitrous** [comment]
> Mentioning Vignette once more is a bit redundant so just title it as "Visit us" or similar in the website, or replace it with something else

I'm not really satisfied with the buttons on the home page just yet since we don't have anything finalized yet. I'll leave it for another PR once we slowly have more things up and running by then.

**Review by sr229 — APPROVED** [review]
Scheduling an Insider build for this now, but before we release this on public, we should get that one sorted.

**Pull request merged**
